### ISSUE TITLE
problem with the MainPage Main_2018-05-30.html

### ISSUE THREAD

**Issue by AndreasVolkmann** [AndreasVolkmann/nhk-easy-kumo#8]
```
19:52:24.012 [main] ERROR Kumo - error
java.lang.Exception: There was a problem with the MainPage Main_2018-05-30.html. Likely because the page didn't load correctly. Try reloading.
	at me.avo.kumo.nhk.pages.MainPage.extractHeadline(MainPage.kt:31) ~[nhk-easy-crawler-1.2.jar:?]
	at me.avo.kumo.nhk.pages.MainPage.getNewsList(MainPage.kt:20) ~[nhk-easy-crawler-1.2.jar:?]
	at me.avo.kumo.nhk.pages.MainPage.get(MainPage.kt:16) ~[nhk-easy-crawler-1.2.jar:?]
	at me.avo.kumo.nhk.Crawler.fetchArticles(Crawler.kt:41) ~[nhk-easy-crawler-1.2.jar:?]
	at me.avo.kumo.nhk.Crawler.fetchAndImport(Crawler.kt:23) ~[nhk-easy-crawler-1.2.jar:?]
	at me.avo.kumo.ApplicationKt.start(Application.kt:24) [nhk-easy-crawler-1.2.jar:?]
	at me.avo.kumo.ApplicationKt.main(Application.kt:11) [nhk-easy-crawler-1.2.jar:?]
Caused by: kotlin.KotlinNullPointerException
	at me.avo.kumo.util.ExtensionsKt.getFirstByTag(Extensions.kt:14) ~[nhk-easy-crawler-1.2.jar:?]
	at me.avo.kumo.nhk.pages.MainPage.extractHeadline(MainPage.kt:23) ~[nhk-easy-crawler-1.2.jar:?]
	... 6 more
```

**Comment by AndreasVolkmann** [comment]
Seems like a temporary bug. Today's page works fine.
